export const factsArray = [
  `On Venus, a day is longer than a year. It takes Venus about 243 Earth days to complete one rotation on its axis, but only about 225 Earth days to orbit the Sun. Plus, it rotates in the opposite direction to most planets, including Earth.`,
  `In the deep, dark clouds of Uranus, scientists think it rains diamonds! That's right, diamonds! It happens because of crazy pressures and temperatures that turn gas into precious gemstones.`,
  `Jupiter has a giant storm that's been going on for more than 350 years! It's like a super-big hurricane, and you could fit three Earths inside it.`,
  `Our air is special! Earth's atmosphere is made mostly of nitrogen and oxygen, and it's just right for us to breathe. It's like a cozy blanket that keeps us safe.`,
  `Olympus Mons is the largest volcano in our solar system, located on Mars. It stands about 13.6 miles (22 kilometers) high, nearly three times the height of Mount Everest.`,
  `Saturn's rings are not solid but are made up of countless particles, ranging in size from tiny grains to large boulders. They are made mostly of water ice with some rocky material.`,
  `Neptune has the strongest winds in our solar system, reaching speeds of over 1,100 miles per hour (1,770 kilometers per hour). These high-speed winds are due to the planet's rapid rotation and its great distance from the Sun.`,
  `The Milky Way galaxy, our home, contains billions of stars. It is estimated that there are more stars in the universe than grains of sand on all the beaches on Earth.`,
  `Black holes are like time machines! Near a black hole, time slows down. It's a bit like being in a magical place where clocks tick slower.`,
  `The Moon is our best friend in space. It always shows us the same side, like a buddy that never turns away. That's why we always see the same face of the Moon from Earth.`,
  `Pluto used to be a planet, but now it's a cool dwarf planet. It's like the smallest member of the solar system family, hanging out way out there.`,
  `Quasars are incredibly bright and energetic sources of light in distant galaxies. They are thought to be powered by supermassive black holes at the centers of these galaxies.`,
  `The universe has some mysterious things called dark matter and dark energy. We can't see them, but they're like the invisible glue holding everything together and making the universe grow.`,
  `Way, way beyond Pluto, there's a place called the Oort Cloud, where comets come from. It's like a big, icy playground for comets, way out in the solar system.`,
  `The Cosmic Microwave Background (CMB) is like a whisper from the Big Bang. It's the oldest sound in the universe, telling us stories about how everything began.`,
  `Scientists have found planets outside our solar system called exoplanets. Some of them might even be a little like Earth. Maybe there's another planet with aliens roaming around!`,
  `Supernovae are explosive events that mark the death of massive stars. These events release an incredible amount of energy, outshining entire galaxies for a short period.`,
  `Between Mars and Jupiter, there is a region called the asteroid belt, which contains numerous small rocky bodies. Contrary to popular belief, the asteroids are spread out, and there is a lot of space between them.`,
  `Pulsars are like space lighthouses. They spin super fast and send out beams of light, just like a cosmic disco ball.`,
  `Gamma-ray bursts are the most energetic events in the universe. They release more energy in a few seconds than our Sun will do in its entire lifetime. The exact cause of these bursts is still not completely understood.`,
  `Mercury experiences extreme temperature swings, with scorching days resembling an oven's heat and freezing nights colder than a typical freezer. Its proximity to the Sun intensifies these extreme conditions.`,
  `Comets are like space snowballs with tails! When they get close to the Sun, the Sun's heat makes them release a sparkling, icy tail that shines like a shooting star.`,
  `If you look up at the night sky, you might find Cassiopeia, a constellation that looks like a giant "W" or "M"! It's like a secret code written in stars`,
  `The Sun is like a gigantic battery in the sky. It gives us light and warmth, and without it, there would be no life on Earth.`,
  `We have friends in space! Satellites and space stations like the International Space Station (ISS) orbit Earth, helping us learn more about our planet and the universe.`,
  `Mars is inhabited by robots! Rovers like Curiosity and Perseverance are like interplanetary adventurers, rolling around Mars, sending back pictures and discoveries.`,
  `Sometimes, the Earth goes between the Sun and the Moon, creating a magical lunar eclipse. The Moon turns red, like it's having a celestial tea party.`,
  `Galaxies come in all shapes and sizes! Some are spirals, like swirling whirlpools, while others are elliptical or irregular. It's like a cosmic art gallery.`,
  `Astronauts embark on space exploration missions, venturing beyond Earth to destinations like the Moon and Mars. Their endeavors contribute to humanity's pursuit of scientific knowledge and space discovery.`,
  `After a supernova explosion, it leaves behind a colorful cloud of gas and dust called a supernova remnant. It's like the universe painting with stardust.`,
  `Jupiter has a big family of moons! There are at least 79 of them, and each one is like a mini-world orbiting the giant planet.`,
  `Earth has a space junkyard! Broken satellites, old rocket stages, and other debris orbit around our planet. It's like a celestial recycling challenge.`,
  `The Hubble Space Telescope is like a space photographer. It captures amazing pictures of distant galaxies, nebulae, and colorful cosmic landscapes.`,
  `Some asteroids are like cosmic superheroes! They help keep Earth safe by deflecting dangerous space rocks that might come too close.`,
  `Nebulas are like celestial baby factories! They're vast clouds of gas and dust where new stars are born, twinkling into life.`,
  `The Sun puts on dazzling light shows! Solar flares are like fireworks on the Sun, creating bursts of light and energy.`,
  `Telescopes are like time machines for astronomers. They let us look back in time by capturing light that traveled billions of years to reach us.`,
  `Neptune is the farthest planet from the Sun and is known for its stunning blue color? The blue comes from the presence of methane in its atmosphere.`,
  `Mars is often called the "Red Planet" because its surface is covered in a layer of iron oxide, giving it a rusty, reddish appearance.`,
  `Saturn's rings are not solid? They are made up of countless icy particles and rocks, creating a dazzling display when viewed from space.`,
  `Venus is often called Earth's "sister planet" because it is similar in size and composition? However, its thick atmosphere traps heat, making it the hottest planet in our solar system.`,
  `Jupiter has the largest magnetosphere in our solar system? It's so powerful that if you could see it, it would appear larger in the night sky than the Moon!`,
  `Mercury has the most extreme temperatures of any planet? During the day, it can get scorching hot, while at night, it becomes freezing cold due to its lack of atmosphere.`,
  `Uranus is a bit of an oddball in our solar system? It rotates on its side, making it the only planet that spins this way. Its unique tilt gives it a peculiar rolling motion as it orbits the Sun.`,
  `Earth's surface is divided into pieces called tectonic plates? These plates are constantly moving, causing earthquakes, volcanic activity, and shaping the landscape over time.`,
  `Pluto, once considered the ninth planet, is now classified as a dwarf planet? It resides in the distant Kuiper Belt, a region beyond Neptune that is home to other icy objects.`,
  `Sunsets on Mars are blue? This is because the fine dust in the Martian atmosphere scatters sunlight in a way that makes the sky appear blue during sunset.`,
  `Ceres, the largest object in the asteroid belt between Mars and Jupiter, is considered a dwarf planet? It's also the only dwarf planet located in the inner solar system.`,
  `Io, one of Jupiter's moons, is the most volcanically active object in our solar system? Its surface is constantly changing due to the eruptions of sulfur and other materials.`,
  `Titan, Saturn's largest moon, has a thick atmosphere primarily composed of nitrogen? It's the only moon in our solar system with a substantial atmosphere.`,
  `Ganymede is the largest moon in our solar system and is even bigger than the planet Mercury? It's one of Jupiter's four Galilean moons.`,
  `Enceladus, one of Saturn's moons, has geysers that shoot icy particles into space? These geysers suggest the presence of a subsurface ocean beneath its icy crust.`,
  `Mercury's Caloris Basin is one of the largest impact basins in the solar system? It was created by a colossal asteroid or comet impact and is filled with smooth plains.`,
  `Venus rotates in the opposite direction to most planets in our solar system? It has a retrograde rotation, making the Sun rise in the west and set in the east.`,
  `Earth's magnetic north is constantly moving? It drifts over time due to changes in the molten iron and nickel within the planet's outer core.`,
  `Olympus Mons on Mars is not only the tallest volcano but also the largest shield volcano in the solar system? It's a colossal geological feature.`,
  `Jupiter's four largest moons—Io, Europa, Ganymede, and Callisto—are known as the Galilean moons? They were discovered by Galileo Galilei in 1610.`,
  `Saturn's north pole has a hexagonal-shaped storm? This unique atmospheric feature is a mysterious and captivating hexagon.`,
  `Uranus rotates on its side at an almost 90-degree angle compared to its orbit around the Sun? This extreme tilt makes for some unusual seasons.`,
  `Earth has a mini-moon called 2020 CD3? It's an asteroid that got temporarily caught in Earth's gravitational pull, making it a natural satellite for a brief period.`,
  `In 2017, astronomers detected an object from another star system passing through our solar system? Named 'Oumuamua, it was the first confirmed interstellar visitor.`,
  `The Cassini spacecraft, which studied Saturn and its moons for over 13 years, concluded its mission with a deliberate plunge into Saturn's atmosphere in 2017? It provided valuable data until the very end.`,
  `Pluto has a heart-shaped feature on its surface? Discovered by NASA's New Horizons mission in 2015, this heart-shaped region is informally named Tombaugh Regio after Pluto's discoverer, Clyde Tombaugh.`,
  `NASA's Voyager 1 spacecraft, launched in 1977, has ventured beyond our solar system into interstellar space? It's the farthest human-made object from Earth.`,
  `Within vast clouds of gas and dust in galaxies, there are regions known as stellar nurseries? These nurseries are where new stars are born, emerging from the gravitational collapse of dense molecular clouds.`,
  `The Hubble Space Telescope has captured mesmerizing deep field images revealing galaxies that existed billions of years ago? These images provide a glimpse into the early stages of the universe's evolution.`,
  `The Milky Way has engaged in galactic cannibalism by consuming smaller satellite galaxies? Evidence of this cosmic feast is seen in the diverse populations of stars and stellar streams coursing through our galaxy.`,
  `Some stars change in brightness over time? These variable stars, such as Cepheid variables, serve as cosmic distance markers, aiding astronomers in measuring vast distances across the universe.`,
  `Quasars are among the most powerful and energetic objects in the cosmos? These active galactic nuclei emit intense radiation as supermassive black holes at their centers consume surrounding material.`,
  `Galaxies aren't scattered randomly in space but are organized into massive structures called superclusters? These superclusters are interconnected by vast cosmic filaments, forming the large-scale structure of the universe.`,
  `When massive stars explode in a supernova, they leave behind colorful remnants of gas and dust? These remnants, visible as intricate nebulae, contribute to the enrichment of interstellar material with heavy elements.`,
  `Gravitational lensing, predicted by Einstein's theory of general relativity, can create optical illusions like Einstein's Cross? This phenomenon occurs when a distant quasar's light is bent by the gravity of a foreground galaxy, producing multiple images of the quasar.`,
  `Galaxies evolve over time through processes such as mergers, interactions, and star formation? The study of different galaxy types helps astronomers unravel the intricate tapestry of cosmic evolution.`,
  `Certain star clusters contain "blue straggler" stars that appear younger and bluer than their counterparts? These stars challenge traditional understanding and are believed to form through stellar interactions within the cluster.`,
  `Most of the mass in the universe is composed of dark matter, a mysterious substance that does not emit, absorb, or reflect light? Its gravitational influence shapes the large-scale structure of the cosmos.`,
  `Star clusters are like cosmic communities where stars are born and evolve together? Open clusters contain younger stars, while globular clusters host older stellar populations.`,
];
